// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

open Types

# 10 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | RPAR
  | LPAR
  | DIV
  | MUL
  | MINUS
  | PLUS
  | INT of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_RPAR
    | TOKEN_LPAR
    | TOKEN_DIV
    | TOKEN_MUL
    | TOKEN_MINUS
    | TOKEN_PLUS
    | TOKEN_INT
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startexpression
    | NONTERM_expression
    | NONTERM_term
    | NONTERM_factor

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | RPAR  -> 1 
  | LPAR  -> 2 
  | DIV  -> 3 
  | MUL  -> 4 
  | MINUS  -> 5 
  | PLUS  -> 6 
  | INT _ -> 7 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_RPAR 
  | 2 -> TOKEN_LPAR 
  | 3 -> TOKEN_DIV 
  | 4 -> TOKEN_MUL 
  | 5 -> TOKEN_MINUS 
  | 6 -> TOKEN_PLUS 
  | 7 -> TOKEN_INT 
  | 10 -> TOKEN_end_of_input
  | 8 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startexpression 
    | 1 -> NONTERM_expression 
    | 2 -> NONTERM_expression 
    | 3 -> NONTERM_expression 
    | 4 -> NONTERM_term 
    | 5 -> NONTERM_term 
    | 6 -> NONTERM_term 
    | 7 -> NONTERM_factor 
    | 8 -> NONTERM_factor 
    | 9 -> NONTERM_factor 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 10 
let _fsyacc_tagOfErrorTerminal = 8

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | RPAR  -> "RPAR" 
  | LPAR  -> "LPAR" 
  | DIV  -> "DIV" 
  | MUL  -> "MUL" 
  | MINUS  -> "MINUS" 
  | PLUS  -> "PLUS" 
  | INT _ -> "INT" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | RPAR  -> (null : System.Object) 
  | LPAR  -> (null : System.Object) 
  | DIV  -> (null : System.Object) 
  | MUL  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 3us; 65535us; 0us; 1us; 13us; 14us; 15us; 16us; 5us; 65535us; 0us; 2us; 3us; 4us; 5us; 6us; 13us; 2us; 15us; 2us; 7us; 65535us; 0us; 7us; 3us; 7us; 5us; 7us; 8us; 9us; 10us; 11us; 13us; 7us; 15us; 7us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 5us; 11us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 3us; 1us; 2us; 3us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 2us; 3us; 4us; 5us; 6us; 1us; 4us; 1us; 4us; 1us; 5us; 1us; 5us; 1us; 7us; 1us; 8us; 1us; 8us; 1us; 9us; 1us; 9us; 1us; 9us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 8us; 10us; 12us; 14us; 16us; 20us; 22us; 24us; 26us; 28us; 30us; 32us; 34us; 36us; 38us; |]
let _fsyacc_action_rows = 18
let _fsyacc_actionTableElements = [|3us; 32768us; 2us; 15us; 5us; 13us; 7us; 12us; 0us; 49152us; 2us; 16387us; 5us; 5us; 6us; 3us; 3us; 32768us; 2us; 15us; 5us; 13us; 7us; 12us; 0us; 16385us; 3us; 32768us; 2us; 15us; 5us; 13us; 7us; 12us; 0us; 16386us; 2us; 16390us; 3us; 10us; 4us; 8us; 3us; 32768us; 2us; 15us; 5us; 13us; 7us; 12us; 0us; 16388us; 3us; 32768us; 2us; 15us; 5us; 13us; 7us; 12us; 0us; 16389us; 0us; 16391us; 3us; 32768us; 2us; 15us; 5us; 13us; 7us; 12us; 0us; 16392us; 3us; 32768us; 2us; 15us; 5us; 13us; 7us; 12us; 1us; 32768us; 1us; 17us; 0us; 16393us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 8us; 12us; 13us; 17us; 18us; 21us; 25us; 26us; 30us; 31us; 32us; 36us; 37us; 41us; 43us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 3us; 3us; 1us; 3us; 3us; 1us; 1us; 2us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 1us; 2us; 2us; 2us; 3us; 3us; 3us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 65535us; 16385us; 65535us; 16386us; 65535us; 65535us; 16388us; 65535us; 16389us; 16391us; 65535us; 16392us; 65535us; 65535us; 16393us; |]
let _fsyacc_reductions ()  =    [| 
# 119 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startexpression));
# 128 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "Parser.fsy"
                                             Plus(_1, _3) 
                   )
# 20 "Parser.fsy"
                 : Expression));
# 140 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 "Parser.fsy"
                                             Minus(_1, _3) 
                   )
# 21 "Parser.fsy"
                 : Expression));
# 152 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'term)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 22 "Parser.fsy"
                                  _1 
                   )
# 22 "Parser.fsy"
                 : Expression));
# 163 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 "Parser.fsy"
                                               Multiplication(_1, _3) 
                   )
# 25 "Parser.fsy"
                 : 'term));
# 175 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "Parser.fsy"
                                                Division(_1, _3) 
                   )
# 26 "Parser.fsy"
                 : 'term));
# 187 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "Parser.fsy"
                                    _1 
                   )
# 27 "Parser.fsy"
                 : 'term));
# 198 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "Parser.fsy"
                                  Number(_1) 
                   )
# 30 "Parser.fsy"
                 : 'factor));
# 209 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : Expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "Parser.fsy"
                                               Negation(_2) 
                   )
# 31 "Parser.fsy"
                 : 'factor));
# 220 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : Expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "Parser.fsy"
                                                   _2 
                   )
# 32 "Parser.fsy"
                 : 'factor));
|]
# 232 "Parser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 11;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let expression lexer lexbuf : Expression =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
